services:
  prometheus:
    image: prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    volumes:
      - prometheus_data:/var/lib/prometheus
    restart: always
    extra_hosts:   #access host machine from inside container      deleted to use docker's network
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    build:
      context: ./grafana
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  grafana_data:
  prometheus_data:
