global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9100
- job_name: grafana
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - grafana:9100
- job_name: vps
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.17.0.1:9091
- job_name: 'cadvisor'
  # Prometheus peut résoudre le nom 'cadvisor' via le réseau de compose
  static_configs:
    - targets: ['cadvisor:8080']

rule_files:
  - "/prometheus/alert_rules.yml"
